language: rust

rust:
  - nightly
  - stable

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cd webxr; cargo build --features=glwindow
  - cd webxr; cargo build --features=ipc,glwindow

notifications:
  webhooks: http://build.servo.org:54856/travis
